
#ifndef	___CONVERTER___
#include "system.h"
#include "ishikari.h"
#endif


#define	o	0xff
#define	S	5

/********************
    ステージデータ
 ********************/
const
BYTE	stage_data[][FIELD_H][FIELD_W - FIELD_H/2] =
{
	{
		{ o,o,o,o,1,o,o,o},
		{o,o,o,o,o,o,o,o },
		{ o,o,o,0,o,0,o,o},
		{o,o,o,o,o,o,o,o },
		{ S,o,1,o,0,o,1,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,2,o,3,o,o},
		{o,o,o,o,0,0,o,o },
		{ S,o,1,0,o,0,1,o},
		{o,o,o,o,0,0,o,o },
		{ o,o,o,3,o,2,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,o,o,o,o},
		{o,o,1,o,1,o,1,o },
		{ o,o,o,o,o,o,o,o},
		{S,1,o,1,o,1,o,1 },
		{ o,o,o,o,o,o,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,o,o,o,o},
		{o,o,o,o,o,1,o,o },
		{ o,o,S,o,3,2,o,o},
		{o,o,o,o,3,0,2,o },
		{ o,o,o,2,1,1,3,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,1,o,1,o,1,o},
		{o,o,o,o,o,o,o,o },
		{ o,o,o,1,o,1,o,o},
		{o,o,o,o,o,o,o,o },
		{ o,S,1,o,1,o,1,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,o,o,o,o},
		{o,o,2,o,2,o,o,o },
		{ S,o,2,o,2,o,o,o},
		{o,o,o,2,o,2,o,o },
		{ o,o,o,o,o,o,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,o,o,o,o},
		{o,o,o,1,1,o,o,o },
		{ o,o,o,0,o,o,o,o},
		{o,o,0,o,o,0,o,o },
		{ o,1,1,S,1,1,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,o,o,o,o},
		{o,o,1,o,1,o,1,o },
		{ o,1,1,1,1,1,1,o},
		{S,o,1,o,1,o,1,o },
		{ o,o,o,o,o,o,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,o,3,o,o},
		{o,o,o,o,o,3,o,o },
		{ o,o,o,o,3,o,2,o},
		{o,o,o,o,3,o,o,o },
		{ o,S,o,3,o,2,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,3,o,o,o,o,o},
		{S,o,3,3,o,o,o,o },
		{ o,3,3,o,o,3,3,o},
		{o,o,o,o,o,3,3,o },
		{ o,o,o,o,o,3,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,o,o,o,o},
		{o,S,o,2,o,o,3,o },
		{ o,o,o,2,o,3,o,o},
		{o,o,2,o,2,3,o,3 },
		{ o,o,o,o,o,o,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,1,1,o,o},
		{o,o,o,o,1,1,o,o },
		{ o,S,o,1,1,o,o,o},
		{o,o,o,o,1,1,o,o },
		{ o,o,o,o,1,1,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,o,o,o,o},
		{o,S,o,3,1,2,o,o },
		{ o,o,3,o,o,2,o,o},
		{o,o,3,1,1,1,2,o },
		{ o,o,o,o,o,o,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,S,o,3,o,2,o,o},
		{o,o,o,3,o,o,2,o },
		{ o,o,2,o,o,o,2,o},
		{o,o,o,2,o,o,3,o },
		{ o,o,o,2,o,3,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ S,o,1,1,1,1,o,o},
		{o,o,o,o,o,o,o,o },
		{ o,o,1,1,1,1,o,o},
		{o,o,o,o,o,o,o,o },
		{ o,o,1,1,1,1,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,3,3,o,o},
		{o,o,o,o,3,3,o,o },
		{ o,o,S,o,3,o,o,o},
		{o,o,o,o,3,3,o,o },
		{ o,o,o,3,3,o,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,3,o,3,o},
		{o,o,o,o,3,o,3,o },
		{ S,o,o,3,o,3,o,o},
		{o,o,o,3,o,3,o,o },
		{ o,o,o,o,o,o,o,o},
		{o,o,3,o,3,o,o,o },
	},
	{
		{ o,o,1,1,1,1,1,o},
		{o,o,o,o,o,o,o,o },
		{ S,o,1,o,0,o,1,o},
		{o,o,o,o,o,o,o,o },
		{ o,o,1,1,1,1,1,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,o,o,o,o},
		{o,o,o,1,1,1,1,o },
		{ o,S,2,o,o,o,3,o},
		{o,o,o,2,o,o,3,o },
		{ o,o,o,2,1,3,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,o,o,o,o},
		{o,o,o,2,o,3,2,o },
		{ S,o,3,2,3,o,2,o},
		{o,o,3,o,3,o,o,2 },
		{ o,3,1,o,o,o,1,2},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,o,o,o,o},
		{S,1,1,1,1,1,1,1 },
		{ o,3,o,o,o,o,o,o},
		{o,1,1,1,1,1,1,1 },
		{ o,o,o,o,o,o,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,1,1,1,1,1,o,o},
		{o,o,2,o,o,3,o,o },
		{ S,o,2,0,o,o,o,o},
		{o,o,3,o,o,2,o,o },
		{ o,1,1,1,1,1,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,2,o,1,1,o,3,o},
		{o,o,2,o,1,o,3,o },
		{ o,o,2,0,0,3,o,o},
		{o,o,o,2,0,3,o,o },
		{ S,o,o,2,3,o,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,3,o,3,o,3},
		{o,o,o,o,0,o,0,o },
		{ S,o,3,o,0,o,3,o},
		{o,o,o,0,o,0,o,o },
		{ o,3,o,3,o,3,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,3,0,0,0,0,2,o},
		{o,1,1,1,1,1,1,1 },
		{ o,o,o,o,o,o,o,o},
		{o,1,1,1,1,1,1,1 },
		{ S,2,0,0,0,0,3,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,3,1,1,2,o,o},
		{o,o,3,2,o,o,o,o },
		{ o,o,2,1,1,2,o,o},
		{o,o,o,o,o,2,3,o },
		{ S,o,2,1,1,3,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,o,o,o,o},
		{S,o,1,1,1,1,1,o },
		{ o,2,0,3,2,0,3,o},
		{o,o,2,3,o,2,3,o },
		{ o,o,o,o,o,o,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,3,o,o,3,o},
		{o,o,o,3,1,1,3,o },
		{ S,o,3,o,o,3,o,o},
		{o,o,3,1,1,3,o,o },
		{ o,3,o,o,3,o,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ S,o,o,o,2,o,o,o},
		{o,o,o,2,o,2,o,o },
		{ o,2,o,2,o,2,o,o},
		{2,o,2,o,2,o,2,o },
		{ 2,o,2,o,2,o,2,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,2,o,3,o,o},
		{o,o,o,1,1,3,o,o },
		{ o,S,o,o,3,1,1,o},
		{o,o,o,o,3,o,2,o },
		{ o,o,o,3,o,o,o,o},
		{o,o,o,0,o,o,o,o },
	},
	{
		{ S,o,3,3,2,o,o,o},
		{o,o,3,3,o,2,o,o },
		{ o,3,3,o,o,o,0,o},
		{o,o,2,2,o,3,o,o },
		{ o,o,2,2,3,o,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,1,o,o,o,o},
		{S,1,o,2,3,o,1,o },
		{ 2,3,o,0,o,2,3,o},
		{o,0,o,3,2,o,0,o },
		{ 3,2,o,1,o,3,2,o},
		{o,1,o,o,o,o,1,o },
	},
	{
		{ o,o,2,o,1,o,3,o},
		{o,o,o,o,0,0,o,o },
		{ S,1,o,0,o,0,o,1},
		{o,o,o,o,0,0,o,o },
		{ o,o,3,o,1,o,2,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,2,o,2,o,o},
		{o,o,2,o,2,o,2,o },
		{ o,o,2,o,o,o,o,o},
		{S,2,o,2,o,o,2,o },
		{ o,2,o,1,1,1,3,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,S,o,2,o,o},
		{o,o,o,o,2,o,2,o },
		{ o,o,2,o,2,o,2,o},
		{o,2,o,2,o,2,o,o },
		{ o,2,o,2,o,o,o,o},
		{o,o,2,o,o,o,o,o },
	},
	{
		{ o,o,o,3,o,o,o,o},
		{o,o,o,3,o,o,o,o },
		{ o,o,3,o,o,2,o,o},
		{S,o,3,1,1,o,2,o },
		{ o,o,o,o,o,o,2,o},
		{o,o,o,o,1,1,1,2 },
	},
	{
		{ o,o,2,o,3,2,o,o},
		{o,o,o,2,3,o,2,o },
		{ o,S,o,1,o,0,1,o},
		{o,o,o,3,2,o,3,o },
		{ o,o,3,o,2,3,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ S,o,1,1,o,3,3,o},
		{o,o,1,1,o,3,3,o },
		{ o,o,o,o,o,o,o,o},
		{o,o,3,3,o,1,1,o },
		{ o,3,3,o,1,1,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,o,o,o,o},
		{S,3,2,o,o,3,2,o },
		{ 3,o,2,o,3,o,3,o},
		{2,o,3,o,3,o,3,o },
		{ 2,3,o,3,o,3,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,3,2,o,o,o,o},
		{S,o,3,0,2,o,o,o },
		{ o,o,o,3,o,o,o,o},
		{o,o,o,3,1,1,1,3 },
		{ o,o,3,3,o,o,3,o},
		{o,o,o,2,1,1,3,o },
	},
	{
		{ S,1,1,1,1,1,1,o},
		{o,o,1,o,o,o,1,o },
		{ o,o,0,0,0,0,o,o},
		{o,o,1,o,o,o,1,o },
		{ o,1,1,1,1,1,1,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,o,3,3,o,o},
		{o,o,o,o,3,3,o,o },
		{ S,o,1,1,o,1,1,o},
		{o,o,1,1,o,1,1,o },
		{ o,o,o,3,3,o,o,o},
		{o,o,o,3,3,o,o,o },
	},
	{
		{ o,1,1,o,o,o,1,1},
		{o,o,o,o,3,2,o,o },
		{ o,1,1,o,o,o,1,1},
		{o,o,o,o,2,3,o,o },
		{ S,1,1,o,o,o,1,1},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,1,1,2,o,o},
		{o,o,3,o,0,o,2,o },
		{ o,3,0,o,1,1,2,o},
		{o,2,o,3,o,o,o,o },
		{ o,2,3,o,S,o,3,o},
		{o,o,2,o,o,o,o,o },
	},
	{
		{ o,S,o,3,o,1,1,1},
		{o,o,o,3,o,3,o,2 },
		{ o,o,3,o,0,o,2,o},
		{o,o,3,o,3,o,2,o },
		{ o,1,1,1,o,2,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ 1,1,o,0,o,1,1,o},
		{o,0,o,1,1,o,0,o },
		{ o,o,o,o,o,o,o,o},
		{o,o,0,o,1,1,o,0 },
		{ o,1,1,S,0,o,1,1},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,3,1,o,3,1},
		{o,o,o,3,o,o,3,o },
		{ S,0,0,2,0,0,2,0},
		{o,o,o,3,o,o,3,o },
		{ o,1,3,o,1,3,o,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ o,o,o,3,o,2,o,o},
		{o,3,o,2,o,o,3,o },
		{ 2,o,o,3,o,2,o,o},
		{S,3,o,2,o,o,3,o },
		{ 2,o,o,3,o,2,o,o},
		{o,3,o,2,o,o,o,o },
	},
	{
		{ o,o,2,0,2,o,1,1},
		{o,o,o,2,0,2,o,1 },
		{ o,S,o,2,0,2,o,o},
		{o,o,1,o,2,0,2,o },
		{ o,1,1,o,2,0,2,o},
		{o,o,o,o,o,o,o,o },
	},
	{
		{ S,1,1,1,1,1,1,o},
		{o,1,o,1,o,1,1,1 },
		{ 1,o,o,o,o,1,1,1},
		{1,o,0,o,0,o,1,o },
		{ 1,o,o,o,o,1,o,1},
		{1,1,o,o,o,1,1,o },
	},

#if 0
	{
		{ o,o,o,o,o,o,o,o},
		{o,o,o,o,o,o,o,o },
		{ o,o,o,o,o,o,o,o},
		{o,o,o,o,o,o,o,o },
		{ o,o,o,o,o,o,o,o},
		{o,o,o,o,o,o,o,o },
	},
#endif
};
